/**
 * Mapeamento de nomes de seleções (como estão no banco) para nomes em pt-BR.
 */
const countryNameMap: Record<string, string> = {
  'Afghanistan': 'Afeganistão',
  'Albania': 'Albânia',
  'Algeria': 'Argélia',
  'Argentina': 'Argentina',
  'Australia': 'Austrália',
  'Austria': 'Áustria',
  'Belgium': 'Bélgica',
  'Bolivia': 'Bolívia',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  'Brazil': 'Brasil',
  'Cabo Verde': 'Cabo Verde',
  'Cameroon': 'Camarões',
  'Canada': 'Canadá',
  'Chile': 'Chile',
  'China PR': 'China',
  'Colombia': 'Colômbia',
  'Congo DR': 'Congo (RDC)',
  'Costa Rica': 'Costa Rica',
  'Croatia': 'Croácia',
  'Cuba': 'Cuba',
  'Curaçao': 'Curaçao',
  'Czechia': 'República Tcheca',
  'Czech Republic': 'República Tcheca',
  'Denmark': 'Dinamarca',
  'Ecuador': 'Equador',
  'Egypt': 'Egito',
  'England': 'Inglaterra',
  'Finland': 'Finlândia',
  'France': 'França',
  'Germany': 'Alemanha',
  'Ghana': 'Gana',
  'Greece': 'Grécia',
  'Haiti': 'Haiti',
  'Honduras': 'Honduras',
  'Hungary': 'Hungria',
  'Iceland': 'Islândia',
  'India': 'Índia',
  'Indonesia': 'Indonésia',
  'IR Iran': 'Irã',
  'Iran': 'Irã',
  'Iraq': 'Iraque',
  'Ireland': 'Irlanda',
  'Israel': 'Israel',
  'Italy': 'Itália',
  'Ivory Coast': 'Costa do Marfim',
  "Côte d'Ivoire": 'Costa do Marfim',
  'Jamaica': 'Jamaica',
  'Japan': 'Japão',
  'Jordan': 'Jordânia',
  'Kenya': 'Quênia',
  'Korea Republic': 'Coreia do Sul',
  'South Korea': 'Coreia do Sul',
  'Mexico': 'México',
  'Morocco': 'Marrocos',
  'Netherlands': 'Países Baixos',
  'New Zealand': 'Nova Zelândia',
  'Nigeria': 'Nigéria',
  'North Macedonia': 'Macedônia do Norte',
  'Norway': 'Noruega',
  'Oman': 'Omã',
  'Panama': 'Panamá',
  'Paraguay': 'Paraguai',
  'Peru': 'Peru',
  'Philippines': 'Filipinas',
  'Poland': 'Polônia',
  'Portugal': 'Portugal',
  'Qatar': 'Catar',
  'Romania': 'Romênia',
  'Russia': 'Rússia',
  'Saudi Arabia': 'Arábia Saudita',
  'Scotland': 'Escócia',
  'Senegal': 'Senegal',
  'Serbia': 'Sérvia',
  'Slovakia': 'Eslováquia',
  'Slovenia': 'Eslovênia',
  'South Africa': 'África do Sul',
  'Spain': 'Espanha',
  'Sweden': 'Suécia',
  'Switzerland': 'Suíça',
  'Thailand': 'Tailândia',
  'Tunisia': 'Tunísia',
  'Türkiye': 'Turquia',
  'Turkey': 'Turquia',
  'Ukraine': 'Ucrânia',
  'United Arab Emirates': 'Emirados Árabes Unidos',
  'Uruguay': 'Uruguai',
  'USA': 'EUA',
  'United States': 'EUA',
  'Uzbekistan': 'Uzbequistão',
  'Venezuela': 'Venezuela',
  'Vietnam': 'Vietnã',
  'Wales': 'País de Gales',
}

/**
 * Retorna o nome da seleção traduzido para pt-BR.
 * Se não houver tradução, retorna o nome original.
 *
 * @param teamName - Nome do time como está no banco (ex: "Brazil", "Korea Republic")
 */
export function getTeamName(teamName: string): string {
  return countryNameMap[teamName] ?? teamName
}

/**
 * Mapeamento de nomes de seleções (como estão no banco) para códigos ISO 3166-1 alpha-2.
 * Usado para gerar URLs de bandeiras via flagcdn.com
 */
const countryCodeMap: Record<string, string> = {
  'Afghanistan': 'af',
  'Albania': 'al',
  'Algeria': 'dz',
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Belgium': 'be',
  'Bolivia': 'bo',
  'Bosnia and Herzegovina': 'ba',
  'Brazil': 'br',
  'Cameroon': 'cm',
  'Canada': 'ca',
  'Chile': 'cl',
  'China PR': 'cn',
  'Colombia': 'co',
  'Congo DR': 'cd',
  'Costa Rica': 'cr',
  'Croatia': 'hr',
  'Cuba': 'cu',
  'Curaçao': 'cw',
  'Czechia': 'cz',
  'Czech Republic': 'cz',
  'Denmark': 'dk',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'England': 'gb-eng',
  'Finland': 'fi',
  'France': 'fr',
  'Germany': 'de',
  'Ghana': 'gh',
  'Greece': 'gr',
  'Haiti': 'ht',
  'Honduras': 'hn',
  'Hungary': 'hu',
  'Iceland': 'is',
  'India': 'in',
  'Indonesia': 'id',
  'IR Iran': 'ir',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Ireland': 'ie',
  'Israel': 'il',
  'Italy': 'it',
  'Ivory Coast': 'ci',
  "Côte d'Ivoire": 'ci',
  'Jamaica': 'jm',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Kenya': 'ke',
  'Korea Republic': 'kr',
  'South Korea': 'kr',
  'Mexico': 'mx',
  'Morocco': 'ma',
  'Netherlands': 'nl',
  'New Zealand': 'nz',
  'Nigeria': 'ng',
  'North Macedonia': 'mk',
  'Norway': 'no',
  'Oman': 'om',
  'Panama': 'pa',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Philippines': 'ph',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Romania': 'ro',
  'Russia': 'ru',
  'Saudi Arabia': 'sa',
  'Scotland': 'gb-sct',
  'Senegal': 'sn',
  'Serbia': 'sr',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'South Africa': 'za',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Thailand': 'th',
  'Tunisia': 'tn',
  'Türkiye': 'tr',
  'Turkey': 'tr',
  'Ukraine': 'ua',
  'United Arab Emirates': 'ae',
  'Uruguay': 'uy',
  'USA': 'us',
  'United States': 'us',
  'Uzbekistan': 'uz',
  'Venezuela': 've',
  'Vietnam': 'vn',
  'Wales': 'gb-wls',
}

/**
 * Retorna a URL da bandeira para um nome de seleção.
 * Usa flagcdn.com (gratuito, sem API key, com CDN global).
 *
 * @param teamName - Nome do time como está no banco (ex: "Brazil", "Korea Republic")
 * @param width - Largura da imagem em pixels (default: 80)
 * @returns URL da bandeira ou null se o time não for encontrado
 */
export function getFlagUrl(teamName: string, width = 80): string | null {
  const code = countryCodeMap[teamName]
  if (!code) return null
  return `https://flagcdn.com/w${width}/${code}.png`
}

/**
 * Retorna o código ISO de um time (útil para usar com emoji flags ou outras libs).
 */
export function getCountryCode(teamName: string): string | null {
  return countryCodeMap[teamName] ?? null
}
